# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CommunAphasia' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CommunAphasia
  pod 'Hero'

  target 'CommunAphasiaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CommunAphasiaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
